### Сделайте транспонирование матрицы без использования numpy и других библиотек

In [1]:
def transpose(matrix):

    transposed = []

    for idx in range(len(matrix[0])):
        transposed.append([matrix[jdx][idx] for jdx in range(len(matrix))])

    return transposed

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transpose(matrix)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [2]:
import numpy as np

### Теперь сделайте транспонирование с помощью numpy

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [4]:
# Ваш код здесь
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Сделайте умножение транспонированного input_vector на weights_matrix

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

input_vector = np.array([[0.5], 
                         [0.8]])

weights_matrix = np.array([[0.2, 0.3], 
                           [0.6, -0.1]])

hidden_layer_output = sigmoid(input_vector.T @ weights_matrix)

print(hidden_layer_output)

[[0.64106741 0.51749286]]



### Используя матричные операции, найдите веса линейной регрессии.

Пусть у вас есть следующие данные:

- $ X $ - матрица признаков размерности $ m \times n $, где $ m $ - количество объектов, а $ n $ - количество признаков.
- $ y $ - вектор ответов размерности $ m \times n $

Веса линейной регрессии $ w $ можно найти по формуле:

$  w = (X^T X)^{-1} X^T y  $ (-1 - это обратная матрица)

Напишите функцию, для нахождения $w$


In [6]:
import numpy as np

def compute_weights(X, y):
    xtx = X.T @ X

    if np.linalg.det(xtx) == 0:
        raise ValueError("Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.")
    
    w = np.linalg.inv(xtx) @ X.T @ y

    return w


In [23]:
X = np.array([
    [1, 2, 3, 6, 5, 6],
    [2, 4, 2, 4, 6, 7],
    [3, 6, 4, 8, 7, 8],
    [4, 8, 3, 6, 8, 9],
    [5, 10, 5, 10, 9, 10],
    [6, 12, 1, 2, 10, 11]
])


In [24]:
y = np.random.rand(6, 1)
weights = compute_weights(X, y)

ValueError: Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.

### В том случае, если у матрицы есть линейно зависимые столбцы посчитать веса не получится

In [25]:
X1 = np.array([
    [1, 2, 3, 4, 5, 6],
    [2, 4, 2, 8, 6, 7],
    [3, 6, 4, 12, 7, 8],
    [4, 8, 3, 16, 8, 9],
    [5, 10, 5, 20, 9, 10],
    [6, 12, 1, 24, 10, 11]
])


In [26]:
y1 = np.random.rand(6, 1)
weights = compute_weights(X1, y1)

ValueError: Матрица X^T X необратима. Проверьте наличие коллинеарных признаков.

### Придумайте способ, который может у любой матрицы X найти линейно зависимые столбцы и напишите такую функцию. После этого примените эту функцию к матрице X1 

In [28]:
#Ваш код здесь
# Задачу можно решить несколькими способами, в частности можно найти ранг матрицы A, 
# если он равен её размерности, то матриа не имеет зависимых столбцов
# Можно через svd разложение

def linearly_dependent_columns(X):
    def equal_linearly_dependent_columns(X):
        U, S, Vt = np.linalg.svd(X, full_matrices=False)
        
        for i in range(len(S)):
            if np.isclose(S[i], 0):
                return True
        
        return False


    equal_dependent_columns = equal_linearly_dependent_columns(X)
    print(X)

    if equal_dependent_columns:
        print('В матрице есть линейно зависимые столбцы')
    else:
        print('В матрице нет линейно зависимых столбцов')

linearly_dependent_columns(X)
linearly_dependent_columns(X1)

[[ 1  2  3  6  5  6]
 [ 2  4  2  4  6  7]
 [ 3  6  4  8  7  8]
 [ 4  8  3  6  8  9]
 [ 5 10  5 10  9 10]
 [ 6 12  1  2 10 11]]
В матрице есть линейно зависимые столбцы
[[ 1  2  3  4  5  6]
 [ 2  4  2  8  6  7]
 [ 3  6  4 12  7  8]
 [ 4  8  3 16  8  9]
 [ 5 10  5 20  9 10]
 [ 6 12  1 24 10 11]]
В матрице есть линейно зависимые столбцы
[[1 2]
 [3 5]]
В матрице нет линейно зависимых столбцов


In [13]:
import numpy as np

def find_linearly_dependent_columns(X):
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    print(U, S, Vt)
    linearly_dependent_columns = []
    
    for i in range(len(S)):
        if np.isclose(S[i], 0):
            linearly_dependent_columns.append(i)
    
    return linearly_dependent_columns

# Пример применения к матрице X1
X1 = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])

dependent_columns = find_linearly_dependent_columns(X1)
print("Линейно зависимые столбцы в матрице X1:", dependent_columns)


[[-0.26726124  0.95618289  0.11952286]
 [-0.53452248 -0.04390192 -0.84401323]
 [-0.80178373 -0.28945968  0.52283453]] [1.40000000e+01 1.30016008e-15 0.00000000e+00] [[-0.26726124 -0.53452248 -0.80178373]
 [-0.87287156 -0.21821789  0.43643578]
 [ 0.40824829 -0.81649658  0.40824829]]
Линейно зависимые столбцы в матрице X1: [1, 2]


### Давайте рассмотрим матричное уравнение вида:

### $ AX = B $

### Напишите код, который найдет $X$


In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
X = np.linalg.inv(A) @ B
print("Матрица X:")
print(X)

Матрица X:
[[-3. -4.]
 [ 4.  5.]]


### Напишите код, который находит собственные значения и векторы матрицы A

In [26]:
import numpy as np

A = np.array([[4, -2],
              [1,  3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Собственные значения:")
print(eigenvalues)
print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[3.5+1.32287566j 3.5-1.32287566j]

Собственные векторы:
[[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415-0.54006172j 0.20412415+0.54006172j]]


### Почему числа получились какие-то странные?

In [8]:
# Ответ тут (можно писать любые мысли)

"""
Собственные вектора являются комплексными, потому что комплексными являются собственные значения.
Собственные значения являются комплексными, потому что собственных значений в плоскости действительных чисел нет.
Поэтому ониявляются решением уравнения, которое получается в процессе преобразования
A - λ * E = 0
После преобразования получим матрицу:
4-λ -2
 1  3-λ

=

0

Её детерминант должен быть равен нулю.
Далее получаем квадратное уравнение:  λ^2 - 7*λ + 14 = 0 решением которого являются число комплексной плоксоти
"""

'\nСобственные вектора являются комплексными, потому что комплексными являются собственные значения.\nСобственные значения являются комплексными, потому что являются решением квадратного уравнения, которое получается в процессе преобразования\n\n'